services:
#  elasticsearch:
#    image: docker.elastic.co/elasticsearch/elasticsearch:8.14.1
#    environment:
#      - discovery.type=single-node
#      - ES_JAVA_OPTS=-Xms512m -Xmx512m
#      - ELASTIC_PASSWORD=your_elastic_password
#      - bootstrap.memory_lock=true
#      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
#    ulimits:
#      memlock:
#        soft: -1
#        hard: -1
#    volumes:
#      - ./data/elastic_search_data:/usr/share/elasticsearch/data
#    ports:
#      - 9200:9200
#    networks:
#      - common
#    healthcheck:
#      test: [ "CMD-SHELL", "curl -s http://localhost:9200/_cluster/health | grep -vq '\"status\":\"red\"'" ]
#      interval: 1s
#      timeout: 1s
#      retries: 50

  postgres:
    restart: always
    image: postgres:latest
    volumes:
      - ./data/postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=your_postgres_password
      - POSTGRES_DB=postgres
    networks:
      - common

  redis:
    restart: always
    image: redis:latest
    volumes:
      - ./data/redis_data:/data
    ports:
      - "6379:6379"
    command:
      - --maxmemory 256MB
      - --requirepass your_redis_password
    networks:
      - common

  prometheus:
    restart: always
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./data/prometheus_data:/etc/prometheus
    ports:
      - "9090:9090"
    networks:
      - common

  grafana:
    restart: always
    image: grafana/grafana:latest
    volumes:
      - ./data/grafana_data:/var/lib/grafana
    ports:
      - "3000:3000"
    networks:
      - common

  server:
    build:
      context: .
      target: final
    networks:
      - common
    ports:
      - 4040:4040
    environment:
      - PORT=4040
      - IS_PRODUCTION=false
      - ES_ADDRESSES=["http://elasticsearch:9200"]
      - ES_USERNAME=elastic
      - ES_PASSWORD=your_elastic_password
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=your_postgres_password
      - POSTGRES_DB_NAME=postgres
      - REDIS_ADDRESS=redis:6379
      - REDIS_PASSWORD=your_redis_password
      - FST_ACCESS_KEY=your_fst_access_key
      - FST_REFRESH_KEY=your_fst_refresh_key
      - PROMETHEUS_ADDRESS=prometheus:9090
    depends_on:
#      elasticsearch:
#        condition: service_started
      postgres:
        condition: service_started
      redis:
        condition: service_started
      prometheus:
        condition: service_started
networks:
  common:
    driver: bridge